# Generated by Django 3.2.21 on 2023-09-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='userfile/'),
        ),
    ]
