# Generated by Django 3.2.21 on 2023-09-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_exceldemo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceldemo',
            name='number',
            field=models.IntegerField(max_length=12),
        ),
    ]
